apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"gl-api"},"name":"gl-api-service","namespace":"default"},"spec":{"ports":[{"port":8080,"protocol":"TCP"}],"selector":{"app":"gl-api"},"type":"NodePort"}}
  creationTimestamp: 2018-04-05T11:41:29Z
  labels:
    app: gl-api
  name: gl-api-service
  namespace: default
  resourceVersion: "1976"
  selfLink: /api/v1/namespaces/default/services/gl-api-service
  uid: 481035cf-38c6-11e8-a3df-42010a8001e4
spec:
  clusterIP: 10.59.243.175
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30580
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gl-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
