apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"gl-api"},"name":"gl-api-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"gl-api"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"gl-api"}},"spec":{"containers":[{"env":[{"name":"mongo-db-uri","valueFrom":{"configMapKeyRef":{"key":"api-mongouri","name":"gl-config"}}}],"image":"gcr.io/oceanic-isotope-199421/github-zmad5306-gl-api:latest","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/api/actuator/health","port":8080},"initialDelaySeconds":30,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":30},"name":"gl-api","ports":[{"containerPort":8080}],"readinessProbe":{"failureThreshold":5,"httpGet":{"path":"/api/actuator/health","port":8080},"initialDelaySeconds":30,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":30},"resources":{"limits":{"memory":"512Mi"},"requests":{"memory":"256Mi"}}}]}}}}
  creationTimestamp: 2018-04-05T11:41:27Z
  generation: 2
  labels:
    app: gl-api
  name: gl-api-deployment
  namespace: default
  resourceVersion: "3351"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gl-api-deployment
  uid: 46f062bf-38c6-11e8-a3df-42010a8001e4
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gl-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gl-api
    spec:
      containers:
      - env:
        - name: mongo-db-uri
          valueFrom:
            configMapKeyRef:
              key: api-mongouri
              name: gl-config
        image: gcr.io/oceanic-isotope-199421/github-zmad5306-gl-api:33fa226b2c8399735e043723371eb0f76c356623
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
        name: gl-api
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2018-04-05T11:43:26Z
    lastUpdateTime: 2018-04-05T11:43:26Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-04-05T11:41:27Z
    lastUpdateTime: 2018-04-05T11:58:11Z
    message: ReplicaSet "gl-api-deployment-67bc6975cf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
