apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"StatefulSet","metadata":{"annotations":{},"name":"mongo","namespace":"default"},"spec":{"replicas":2,"serviceName":"mongo","template":{"metadata":{"labels":{"environment":"test","role":"mongo"}},"spec":{"containers":[{"command":["mongod","--replSet","rs0","--smallfiles","--noprealloc","--bind_ip_all"],"image":"mongo","name":"mongo","ports":[{"containerPort":27017}],"volumeMounts":[{"mountPath":"/data/db","name":"mongo-persistent-storage"}]},{"env":[{"name":"MONGO_SIDECAR_POD_LABELS","value":"role=mongo,environment=test"}],"image":"cvallance/mongo-k8s-sidecar","name":"mongo-sidecar"}],"terminationGracePeriodSeconds":10}},"volumeClaimTemplates":[{"metadata":{"annotations":{"volume.beta.kubernetes.io/storage-class":"fast"},"name":"mongo-persistent-storage"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"128Mi"}}}}]}}
  creationTimestamp: 2018-04-05T11:41:38Z
  generation: 1
  labels:
    environment: test
    role: mongo
  name: mongo
  namespace: default
  resourceVersion: "2229"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/mongo
  uid: 4d0e3c97-38c6-11e8-a3df-42010a8001e4
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      environment: test
      role: mongo
  serviceName: mongo
  template:
    metadata:
      creationTimestamp: null
      labels:
        environment: test
        role: mongo
    spec:
      containers:
      - command:
        - mongod
        - --replSet
        - rs0
        - --smallfiles
        - --noprealloc
        - --bind_ip_all
        image: mongo
        imagePullPolicy: Always
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongo-persistent-storage
      - env:
        - name: MONGO_SIDECAR_POD_LABELS
          value: role=mongo,environment=test
        image: cvallance/mongo-k8s-sidecar
        imagePullPolicy: Always
        name: mongo-sidecar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
      creationTimestamp: null
      name: mongo-persistent-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 128Mi
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 2
  currentRevision: mongo-7877f465c5
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updateRevision: mongo-7877f465c5
