apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"gl-ui"},"name":"gl-ui-deployment","namespace":"default"},"spec":{"minReadySeconds":5,"replicas":2,"selector":{"matchLabels":{"app":"gl-ui"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"gl-ui"}},"spec":{"containers":[{"image":"gcr.io/oceanic-isotope-199421/github-zmad5306-gl-ui:latest","name":"gl-ui","ports":[{"containerPort":80}],"resources":{"limits":{"memory":"256Mi"},"requests":{"memory":"128Mi"}}}]}}}}
  creationTimestamp: 2018-04-05T11:41:56Z
  generation: 2
  labels:
    app: gl-ui
  name: gl-ui-deployment
  namespace: default
  resourceVersion: "3280"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gl-ui-deployment
  uid: 583de5c0-38c6-11e8-a3df-42010a8001e4
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gl-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gl-ui
    spec:
      containers:
      - image: gcr.io/oceanic-isotope-199421/github-zmad5306-gl-ui:c491d723f03fdb18cf8f490b880fa6b1fc708f77
        imagePullPolicy: Always
        name: gl-ui
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2018-04-05T11:42:13Z
    lastUpdateTime: 2018-04-05T11:42:13Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-04-05T11:41:57Z
    lastUpdateTime: 2018-04-05T11:57:20Z
    message: ReplicaSet "gl-ui-deployment-9dbcccc6c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
