apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"gl-ui"},"name":"gl-ui-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP"}],"selector":{"app":"gl-ui"},"type":"NodePort"}}
  creationTimestamp: 2018-04-05T11:42:00Z
  labels:
    app: gl-ui
  name: gl-ui-service
  namespace: default
  resourceVersion: "2101"
  selfLink: /api/v1/namespaces/default/services/gl-ui-service
  uid: 5a618d7b-38c6-11e8-a3df-42010a8001e4
spec:
  clusterIP: 10.59.249.47
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32114
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gl-ui
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
