apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gl-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "gl-staging-ip"
    kubernetes.io/ingress.allow-http: "false"
    ingress.gcp.kubernetes.io/pre-shared-cert: "gl-staging-cert"
spec:
  rules:
    - host: glstaging.zacharymaddox.us
      http:
        paths:
        - path: /*
          backend:
            serviceName: gl-ui-service
            servicePort: 80
        - path: /api/*
          backend:
            serviceName: gl-api-service
            servicePort: 8080
      