apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: gl-ui
  name: gl-ui-deployment
  namespace: default
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: gl-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gl-ui
    spec:
      containers:
      - image: gcr.io/oceanic-isotope-199421/github-zmad5306-gl-ui:e27d10774a5c0b9ea83717d7a34228be6e90b51e
        name: gl-ui
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
