apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gl-ui-deployment
  labels:
    app: gl-ui
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gl-ui
  template:
    metadata:
      labels:
        app: gl-ui
    spec:
      containers:
      - name: gl-ui
        image: gcr.io/oceanic-isotope-199421/github-zmad5306-gl-ui:c491d723f03fdb18cf8f490b880fa6b1fc708f77
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi